version: "3.8"

services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        volumes:
            -  db:/var/lib/mysql
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: "yes"
            MARIADB_DATABASE: psychic-carnival
            MARIADB_USER: psychic-carnival
            MARIADB_PASSWORD: psychic-carnival

    pma:
        image: phpmyadmin
        restart: always
        ports:
            - "3000:80"
        environment:
            PMA_ARBITRARY: true
            PMA_USER: psychic-carnival
            PMA_PASSWORD: psychic-carnival
            PMA_HOST: db

volumes:
    db:
